-- SalesPulse Additional Core Tables
-- Creates the remaining core tables for Phase 1

-- Referrals Table
CREATE TABLE IF NOT EXISTS referrals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id),
  referred_user_id UUID REFERENCES users(id),
  referral_value NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- What_If_Scenarios Table
CREATE TABLE IF NOT EXISTS what_if_scenarios (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id),
  scenario_name TEXT NOT NULL,
  scenario_data JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SIM_Templates Table
CREATE TABLE IF NOT EXISTS sim_templates (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  sim_id UUID NOT NULL REFERENCES sims(id),
  template_name TEXT NOT NULL,
  template_data JSONB NOT NULL,
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Threads Table (for messaging)
CREATE TABLE IF NOT EXISTS threads (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id UUID NOT NULL REFERENCES organizations(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  thread_id UUID NOT NULL REFERENCES threads(id),
  sender_id UUID NOT NULL REFERENCES users(id),
  recipient_id UUID NOT NULL REFERENCES users(id),
  content TEXT NOT NULL,
  sent_at TIMESTAMPTZ DEFAULT NOW(),
  is_read BOOLEAN DEFAULT FALSE
);

-- Feature_Flags Table
CREATE TABLE IF NOT EXISTS feature_flags (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  key TEXT NOT NULL UNIQUE,
  scope TEXT NOT NULL CHECK (scope IN ('global', 'org', 'user')),
  scope_id UUID,
  is_enabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT valid_scope_id CHECK (
    (scope = 'global' AND scope_id IS NULL) OR
    (scope = 'org' AND scope_id IS NOT NULL) OR
    (scope = 'user' AND scope_id IS NOT NULL)
  )
);

-- Documentation comments for additional tables
COMMENT ON TABLE referrals IS 'Tracks referrals generated by users';
COMMENT ON TABLE what_if_scenarios IS 'Saved forecasting scenarios for exploring different sales strategies';
COMMENT ON TABLE sim_templates IS 'Pre-defined templates for each SIM with industry-specific calculations';
COMMENT ON TABLE threads IS 'Message threads for in-app communication';
COMMENT ON TABLE messages IS 'Individual messages within threads';
COMMENT ON TABLE feature_flags IS 'Feature flags for enabling/disabling features at global, org, or user level';
